apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: santequebec-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: santequebec-secret
type: Opaque
stringData:
  # Keep only key names in secretKeyRef.key (DATABASE_URL, JWT_SECRET, etc.).
  # Put the real secret values here.
  databaseUrl: "postgresql://postgresUser:replace-me@localhost:5432/santequebecDB?schema=public"
  jwtSecret: "replace-me"
  adminUser: "admin"
  adminPassHash: "replace-me"
  postgresDb: "santequebecDB"
  postgresUser: "postgresUser"
  postgresPassword: "replace-me"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santequebec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: santequebec
  template:
    metadata:
      labels:
        app: santequebec
    spec:
      containers:
        - name: app
          image: containers.cisco.com/smignacc/santequebec:20260222
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: databaseUrl
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: jwtSecret
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: adminUser
            - name: ADMIN_PASS_HASH
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: adminPassHash
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: postgresDb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: postgresUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: santequebec-secret
                  key: postgresPassword
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: santequebec-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: santequebec
spec:
  selector:
    app: santequebec
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: santequebec
spec:
  to:
    kind: Service
    name: santequebec
  port:
    targetPort: 8080
---
apiVersion: cae.cisco.com/v1
kind: SSOAuthConfig
metadata:
  name: santequebec.cloudapps.cisco.com
  namespace: santequebec
spec:
  provider:
    idp: okta
    sso: application
    cors: application
  contexts:
    - context: /
      contextMatch: prefix
      policyType: public
